force-app/main/default/objects/Case/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/Payment_Info__c.object-meta.xml
<CustomObject>
    <label>Payment Info</label>
    <nameField>
        <displayFormat>PAY-{00000000}</displayFormat>
        <label>Payment Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Info__c/fields/Authorisation_mode__c.field-meta.xml
<CustomField>
    <fullName>Authorisation_mode__c</fullName>
    <label>Authorisation mode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Cancel_method__c.field-meta.xml
<CustomField>
    <fullName>Cancel_method__c</fullName>
    <label>Cancel method</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Cancel_URL__c.field-meta.xml
<CustomField>
    <fullName>Cancel_URL__c</fullName>
    <label>Cancel URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Payment Infos</relationshipLabel>
    <relationshipName>Payment_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Case_Finished__c.field-meta.xml
<CustomField>
    <fullName>Case_Finished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Finished</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <label>Payment Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Delayed_capture__c.field-meta.xml
<CustomField>
    <fullName>Delayed_capture__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delayed capture</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Events_method__c.field-meta.xml
<CustomField>
    <fullName>Events_method__c</fullName>
    <label>Events method</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Events_URL__c.field-meta.xml
<CustomField>
    <fullName>Events_URL__c</fullName>
    <label>Events URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Moto__c.field-meta.xml
<CustomField>
    <fullName>Moto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Next_method__c.field-meta.xml
<CustomField>
    <fullName>Next_method__c</fullName>
    <label>Next method</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Next_URL__c.field-meta.xml
<CustomField>
    <fullName>Next_URL__c</fullName>
    <label>Next URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Next_URL_charge_token_Id__c.field-meta.xml
<CustomField>
    <fullName>Next_URL_charge_token_Id__c</fullName>
    <label>Next URL charge token Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Next_URL_post_method__c.field-meta.xml
<CustomField>
    <fullName>Next_URL_post_method__c</fullName>
    <label>Next URL post method</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Next_URL_post_type__c.field-meta.xml
<CustomField>
    <fullName>Next_URL_post_type__c</fullName>
    <label>Next URL post type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Next_URL_post_URL__c.field-meta.xml
<CustomField>
    <fullName>Next_URL_post_URL__c</fullName>
    <label>Next URL post URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Id__c</fullName>
    <label>Payment Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Number__c</fullName>
    <label>Payment Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Payment_provider__c.field-meta.xml
<CustomField>
    <fullName>Payment_provider__c</fullName>
    <label>Payment provider</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Reference</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Refund_amount_available__c.field-meta.xml
<CustomField>
    <fullName>Refund_amount_available__c</fullName>
    <label>Refund amount available</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Refund_amount_submitted__c.field-meta.xml
<CustomField>
    <fullName>Refund_amount_submitted__c</fullName>
    <label>Refund amount submitted</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Refund_method__c.field-meta.xml
<CustomField>
    <fullName>Refund_method__c</fullName>
    <label>Refund method</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Refund_status__c.field-meta.xml
<CustomField>
    <fullName>Refund_status__c</fullName>
    <label>Refund status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Refund_URL__c.field-meta.xml
<CustomField>
    <fullName>Refund_URL__c</fullName>
    <label>Refund URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Return_URL__c.field-meta.xml
<CustomField>
    <fullName>Return_URL__c</fullName>
    <label>Return URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Self_method__c.field-meta.xml
<CustomField>
    <fullName>Self_method__c</fullName>
    <label>Self method</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Self_URL__c.field-meta.xml
<CustomField>
    <fullName>Self_URL__c</fullName>
    <label>Self URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Payment_Information__mdt/Payment_Information__mdt.object-meta.xml
<CustomObject>
    <label>Payment Information</label>
    <pluralLabel>Payment Informations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Payment_Information__mdt/fields/Authorization_Mode__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Mode__c</fullName>
    <label>Authorization Mode</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Information__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Information__mdt/fields/Moto__c.field-meta.xml
<CustomField>
    <fullName>Moto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Information__mdt/fields/Return_URL__c.field-meta.xml
<CustomField>
    <fullName>Return_URL__c</fullName>
    <label>Return URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/GovPayIntegrationUtil.cls
public with sharing class GovPayIntegrationUtil {
	public static void createPayment(String caseId) {
		Case selectedCase = [SELECT id,Total_Price__c FROM case WHERE Id = :caseId];
		Decimal selectedCasePrice = selectedCase.Total_Price__c.setscale(0);

		GovPayReq request = new GovPayReq();
		String uniqueCode = generateRandomString();
		Payment_Information__mdt paymentInformation = Payment_Information__mdt.getInstance('Createpayment');

		request.amount = selectedCasePrice * 100;
		request.reference = uniqueCode;
		request.language = paymentInformation.Language__c;
		request.moto = paymentInformation.Moto__c;
		request.authorisation_mode = paymentInformation.Authorization_Mode__c;
		request.return_url = paymentInformation.Return_URL__c;
		String requestBody = JSON.serialize(request);
		system.debug(requestBody);

		HttpRequest newPaymentRequest = new HttpRequest();
		newPaymentRequest.setEndpoint('callout:GOV_UK_pay/v1/payments');
		newPaymentRequest.setMethod('POST');
		newPaymentRequest.setHeader('Idempotency-Key', 'Sample12345');
		newPaymentRequest.setHeader('Content-Type', 'application/json');
		newPaymentRequest.setBody(requestBody);
		newPaymentRequest.setTimeout(60000);
		Http http = new Http();
		HTTPResponse response = http.send(newPaymentRequest);
		saveResponse(response.getBody(), caseId);
	}

	public static void saveResponse(String jsonResponse, String caseId) {
		GovPaySaveResponse responseObj = GovPaySaveResponse.parse(jsonResponse);
		createPaymentRecord(responseObj, caseId);
	}

	public static void createPaymentRecord(GovPaySaveResponse response, String caseId) {
		try {
			Payment_Info__c paymentInfo = new Payment_Info__c();
			paymentInfo.Case__c = caseId;
			paymentInfo.Amount__c = response.amount / 100;
			paymentInfo.Description__c = response.description;
			paymentInfo.Reference__c = response.reference;
			paymentInfo.Language__c = response.language;
			paymentInfo.Case_Status__c = response.state.status;
			paymentInfo.Case_Finished__c = response.state.finished;
			paymentInfo.Payment_Id__c = response.payment_id;
			paymentInfo.Payment_provider__c = response.payment_provider;
			paymentInfo.Refund_status__c = response.refund_summary.status;
			paymentInfo.Refund_amount_available__c = response.refund_summary.amount_available / 100;
			paymentInfo.Refund_amount_submitted__c = response.refund_summary.amount_submitted;
			paymentInfo.Delayed_capture__c = response.delayed_capture;
			paymentInfo.Moto__c = response.moto;
			paymentInfo.Return_URL__c = response.return_url;
			paymentInfo.Authorisation_mode__c = response.authorisation_mode;
			paymentInfo.Self_URL__c = response.x_links.self.href;
			paymentInfo.Self_method__c = response.x_links.self.method;
			paymentInfo.Next_URL__c = response.x_links.next_url.href;
			paymentInfo.Next_method__c = response.x_links.next_url.method;
			paymentInfo.Next_URL_post_type__c = response.x_links.next_url_post.type;
			paymentInfo.Next_URL_charge_token_Id__c = response.x_links.next_url_post.params.chargeTokenId;
			paymentInfo.Next_URL_post_URL__c = response.x_links.next_url_post.href;
			paymentInfo.Next_URL_post_method__c = response.x_links.next_url_post.method;
			paymentInfo.Events_URL__c = response.x_links.events.href;
			paymentInfo.Events_method__c = response.x_links.events.method;
			paymentInfo.Refund_URL__c = response.x_links.refunds.href;
			paymentInfo.Refund_method__c = response.x_links.refunds.method;
			paymentInfo.Cancel_URL__c = response.x_links.cancel.href;
			paymentInfo.Cancel_method__c = response.x_links.cancel.method;
			paymentInfo.Payment_Type__c = response.metadata.type;
			paymentInfo.Payment_Number__c = response.metadata.paymentNumber;

			insert paymentInfo;
		} catch (Exception e) {
			System.debug('Error creating record: ' + e.getMessage());
		}
	}

	public static String generateRandomString() {
		final String chars = 'xaxPmno2IDdEwLzbtEvhv6oG1RDT6xQJX3MvF4amaDQ9TUvHgJfdbodlllPTnnuw';
		String randStr = '';
		while (randStr.length() < 8) {
			Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
			randStr += chars.substring(idx, idx + 1);
		}
		DateTime now = DateTime.now();
		String dateTimeString = now.format('yyyyMMddHHmmss');
		randStr += dateTimeString;
		return randStr;
	}
}