force-app/main/default/objects/Payment_Info__c/Payment_Info__c.object-meta.xml
<CustomObject>
    <label>Payment Info</label>
    <nameField>
        <displayFormat>PAY-{00000000}</displayFormat>
        <label>Payment Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Info__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Payment Infos</relationshipLabel>
    <relationshipName>Payment_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Case_Finished__c.field-meta.xml
<CustomField>
    <fullName>Case_Finished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Finished</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <label>Payment Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Info__c/fields/Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Id__c</fullName>
    <label>Payment Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GovPayRestResource.cls
@RestResource(urlMapping='/govPayRestResource/*')
global without sharing class GovPayRestResource {
	@HttpPost
	global static void GovPayRest() {
		try {
			RestRequest request = RestContext.request;
			GovPayWebhookWrapper responseObj = GovPayWebhookWrapper.parse(request.requestBody.toString());
	
			String paymentStatus = responseObj.event_type;
			Boolean paymentFinished = responseObj.Resource.state.finished;
			String paymentId = responseObj.Resource.payment_id;
			String paymentNumber = responseObj.Resource.metadata.paymentNumber;

				Payment_Info__c paymentInformation = [
					SELECT Name, Case_Status__c, Payment_Id__c, Case_Finished__c, Case__c
					FROM Payment_Info__c
					WHERE Payment_Id__c = :paymentId
				];


				if (paymentStatus == 'card_payment_succeeded' && paymentFinished == true) {
					paymentInformation.Case_Status__c = 'Success';
					paymentInformation.Case_Finished__c = true;
				} 
				else {
					if (paymentStatus == 'card_payment_failed') {
						paymentInformation.Case_Status__c = 'Failed';
					} else if (paymentStatus == 'card_payment_expired') {
						paymentInformation.Case_Status__c = 'Expired';
					}

					paymentInformation.Case_Finished__c = true;
				}
				update paymentInformation;

			
		} catch (Exception e) {
			System.debug('Error creating record: ' + e.getMessage());
		}
	}

}